apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: ${ROLE}-tang-clevis
  labels:
    machineconfiguration.openshift.io/role: ${ROLE}
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      luks:
        - name: root
          device: /dev/disk/by-partlabel/root
          clevis:
            tang:
              - url: ${TANG_URL}
                thumbprint: ${THP}
          wipeVolume: true
      filesystems:
        - device: /dev/mapper/root
          format: xfs
          wipeFilesystem: true
          label: root
