{% set ip = config_host if config_host not in ['127.0.0.1', 'localhost'] else baremetal_net|local_ip %}
{% set user = 'root' if config_user == 'apache' else config_user %}
kcli:
 host: {{ ip }}
 user: {{ user }}
