apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: open-cluster-management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: advanced-cluster-management-operatorgroup
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management-subscription
  namespace: open-cluster-management
spec:
  channel: "{{ acm_channel }}"
  name: advanced-cluster-management
  source: {{ "acm-custom-registry" if acm_downstream else "redhat-operator-index" }}
  sourceNamespace: openshift-marketplace
