{% set total_number = namespace(value=0) %}
{% for spoke in ztp_spokes %}
{% set new_value = spoke["virtual_nodes_number"]|default(0) if loop.index0 < index else 0 %}
{% set total_number.value = total_number.value + new_value %}
{% endfor %}
{% set spoke = ztp_spokes[index] %}
{% set spoke_name = spoke.name %}
{% set virtual_nodes_number = spoke["virtual_nodes_number"]|default(0) %}
{% set nodes = spoke["nodes"]|default([]) %}

{% if virtual_nodes_number > 0 %}
{% set extra_nodes = [] %}
{% for num in range(0, virtual_nodes_number) %}
{% do extra_nodes.append({}) %}
{% endfor %}
{% set nodes = extra_nodes + nodes %}
{% endif %}

---
{% for node in nodes %}
{% set num = loop.index0 %}
apiVersion: v1
data:
  password: {{ bmc_password|string|base64 }}
  username: {{ bmc_user|string|base64 }}
kind: Secret
metadata:
  name: {{ cluster }}-ztp-{{ spoke_name }}-bmc-secret-{{ num }}
  namespace: {{ spoke_name }}
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ cluster }}-{{ spoke_name }}-node-{{ num }}
  namespace: {{ spoke_name }}
  labels:
    infraenvs.agent-install.openshift.io: {{ spoke_name }}
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: {{ cluster }}-{{ spoke_name }}-node-{{ num }}
    bmac.agent-install.openshift.io/role: {{ "master" if num < 3 else "worker" }}
spec:
  bmc:
    {% if 'redfish_address' in node %}
    disableCertificateVerification: True
    {% if 'redfish' in node['redfish_address'] or 'idrac' in node['redfish_address'] %}
    address: {{ node['redfish_address'] }}
    {% elif node['model']|default(model) == 'hpe' %}
    address: redfish-virtualmedia://{{ node['redfish_address'] }}/redfish/v1/Systems/1
    {% else %}
    address: idrac-virtualmedia://{{ node['redfish_address'] }}/redfish/v1/Systems/System.Embedded.1
    {% endif %}
    {% else %}
    address: redfish-virtualmedia+http://IP:8000/redfish/v1/Systems/UUID-{{ spoke_name }}-{{ num }}
    {% endif %}
    credentialsName: {{ cluster }}-ztp-{{ spoke_name }}-bmc-secret-{{ num }}
{% if 'provisioning_mac' in node %}
  bootMACAddress: {{ node['provisioning_mac'] }}
{% else %}
  bootMACAddress: {{ ztp_virtual_nodes_baremetal_mac_prefix + ":" + "%02.d" | format(num + total_number.value + 1)| string }}
{% endif %}
  hardwareProfile: unknown
  online: true
  automatedCleaningMode: disabled
  bootMode: {{ 'UEFI' if ztp_uefi else 'legacy' }}
---
{% endfor %}
