{% set spoke = ztp_spokes[index] %}
{% set spoke_name = spoke['name'] %}
{% set virtual_nodes_number = spoke['virtual_nodes_number']|default(0) %}
{% set node = spoke['nodes'][1] if 'nodes' in spoke and spoke['nodes']|length == 2 else {} %}

{% if not virtual_workers %}
{% set virtual_workers_number = 0 %}
{% endif %}

apiVersion: v1
data:
  password: {{ bmc_password|string|base64 }}
  username: {{ bmc_user|string|base64 }}
kind: Secret
metadata:
  name: {{ cluster }}-ztp-{{ spoke_name }}-bmc-secret-1
  namespace: {{ spoke_name }}
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ cluster }}-{{ spoke_name }}-node-1
  namespace: {{ spoke_name }}
  labels:
    infraenvs.agent-install.openshift.io: {{ spoke_name }}
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: {{ cluster }}-{{ spoke_name }}-node-1
    bmac.agent-install.openshift.io/role: worker
spec:
  bmc:
    {% if 'redfish_address' in node %}
    disableCertificateVerification: True
    {% if node['redfish_address'].startswith('redfish-') or node['redfish_address'].startswith('idrac-') %}
    address: {{ node['redfish_address'] }}
    {% elif node['model']|default(model) in ['hp', 'hpe', 'supermicro'] %}
    address: redfish-virtualmedia://{{ node['redfish_address'] }}/redfish/v1/Systems/1
    {% else %}
    address: idrac-virtualmedia://{{ node['redfish_address'] }}/redfish/v1/Systems/System.Embedded.1
    {% endif %}
    {% else %}
    address: redfish-virtualmedia+http://CHANGEME:9000/redfish/v1/Systems/kcli/{{ cluster }}-{{ spoke_name }}-node-1
    {% endif %}
    credentialsName: {{ cluster }}-ztp-{{ spoke_name }}-bmc-secret-1
{% if 'provisioning_mac' in node %}
  bootMACAddress: {{ node['provisioning_mac'] }}
{% elif baremetal_macs and baremetal_macs|length > virtual_ctlplanes_number + virtual_workers_number + index + 1 %}
  bootMACAddress: {{ baremetal_macs[virtual_ctlplanes_number + virtual_workers_number + index +1] }}
{% else %}
  bootMACAddress: {{ ztp_virtual_nodes_baremetal_mac_prefix + ":" + "%02.d" | format(1 + index + 1)| string }}
{% endif %}
  hardwareProfile: unknown
  online: true
  automatedCleaningMode: disabled
  bootMode: {{ node['boot_mode']|default('UEFI' if ztp_uefi else 'legacy') }}
{% if 'disk' in node %}
  rootDeviceHints:
    deviceName: "/dev/{{ node['disk'] | basename }}"
{% elif 'hctl' in node  %}
  rootDeviceHints:
    hctl: "{{ node['hctl'] }}"
{% elif 'serial' in node %}
  rootDeviceHints:
    serialNumber: "{{ node['serial'] }}"
{% elif 'wwn' in node %}
  rootDeviceHints:
    wwn: "{{ node['wwn'] }}"
{% endif %}
---
