kind: ConfigMap
apiVersion: v1
metadata:
  name: extra-manifests-ztp
  namespace: ${SPOKE}
data:
  99-hack-nodeip-configuration.yaml: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        name: hack-nodeip-configuration
        labels:
          machineconfiguration.openshift.io/role: master
      spec:
        config:
          ignition:
            version: 3.2.0
          systemd:
            units:
            - name: nodeip-configuration.service
              enabled: true
              contents: |
                [Unit]
                Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
                # This only applies to VIP managing environments where the kubelet and crio IP
                # address picking logic is flawed and may end up selecting an address from a
                # different subnet or a deprecated address
                Wants=network-online.target crio-wipe.service
                After=network-online.target ignition-firstboot-complete.service crio-wipe.service
                Before=kubelet.service crio.service
                [Service]
                # Need oneshot to delay kubelet
                Type=oneshot
                # Would prefer to do Restart=on-failure instead of this bash retry loop, but
                # the version of systemd we have right now doesn't support it. It should be
                # available in systemd v244 and higher.
                ExecStart=/bin/bash -c " \
                  until \
                  /usr/bin/podman run --rm \
                  --authfile /var/lib/kubelet/config.json \
                  --net=host \
                  --volume /etc/systemd/system:/etc/systemd/system:z \
                  quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7c94e6c2564196855c3e9d47f1ac5bdee4c78059e36b0a83cd6a0e8d7e71ea10 \
                  node-ip \
                  set --retry-on-failure \
                  2620:52:0:1302::1; \
                  do \
                  sleep 5; \
                  done"
                ExecStart=/bin/systemctl daemon-reload
                [Install]
                WantedBy=multi-user.target
