apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v${MINOR}
  namespace: multicluster-engine
spec:
  releaseImage: ${RELEASE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  LOG_LEVEL: "debug"
{% if ztp_disable_validations %}
  DISABLED_HOST_VALIDATIONS: belongs-to-majority-group,belongs-to-machine-cidr
{% endif %}
{% if disconnected %}
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.ci.openshift.org,registry.redhat.io"
{% endif %}
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  namespace: multicluster-engine
  name: agent
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: 'assisted-service-config'
spec:
{% if ztp_pxe %}
  iPXEHTTPRoute: enabled
{% endif %}
  databaseStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
  filesystemStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
{% if disconnected %}
  mirrorRegistryRef:
    name: "custom-registries"
{% endif %}
  osImages:
    - openshiftVersion: "${MINOR}"
      url: "http://${BAREMETAL_IP}/rhcos-live.x86_64.iso"
      rootFSUrl: "http://${BAREMETAL_IP}/rhcos-live-rootfs.x86_64.img"
      cpuArchitecture: "x86_64"
      version: "${VERSION}"
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: assisted-deployment-ssh-private-key
  namespace: multicluster-engine
type: Opaque
stringData:
  ssh-privatekey: |
${SSH_PRIV_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: multicluster-engine
stringData:
  .dockerconfigjson: '${PULLSECRET}'
  type: kubernetes.io/dockerconfigjson
{% if disconnected %}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
${CA_CERT}
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      mirror-by-digest-only = true
    
      [[registry.mirror]]
        location = "${LOCAL_REGISTRY}/${DISCONNECTED_PREFIX_IMAGES}"

    [[registry]]
      prefix = ""
      location = "registry.ci.openshift.org/ocp/release"
      mirror-by-digest-only = true
    
      [[registry.mirror]]
        location = "${LOCAL_REGISTRY}/${DISCONNECTED_PREFIX_IMAGES}"
    
    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      mirror-by-digest-only = true
    
      [[registry.mirror]]
        location = "${LOCAL_REGISTRY}/${DISCONNECTED_PREFIX}"

${REGISTRIES}
{% endif %}
