{% for num in range(0, virtual_workers_number) %}
{% set node_name = cluster + "-worker-" + num|string  %}
apiVersion: v1
data:
  password: {{ bmc_password|string|base64 }}
  username: {{ bmc_user|string|base64 }}
kind: Secret
metadata:
  manager: baremetal-operator
  name: {{ cluster }}-worker-{{ num }}-bmc-secret
  namespace: openshift-machine-api
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ cluster }}-worker-{{ num }}
  namespace: openshift-machine-api
spec:
  bmc:
    address: redfish-virtualmedia+http://{{ config_host if config_host != '127.0.0.1' else baremetal_net|local_ip }}:8000/redfish/v1/Systems/{{ node_name|kcli_info('id') }}
    credentialsName: {{ cluster }}-worker-{{ num }}-bmc-secret
  bootMACAddress: {{ virtual_workers_baremetal_mac_prefix }}:{{ '%02d' | format(num + 1) }}
  hardwareProfile: unknown
  online: true
{% endfor %}
