apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kcli-plan-baremetal-lab
spec:
  pipelineRef:
    name: kcli-plan-baremetal-lab
  params:
    - name: plan
      value: "lab"
    - name: paramfile
      value: "lab.yml"
    - name: commit
      value: "main"
    - name: launch_steps
      value: "true"
    - name: deploy_openshift
      value: "true"
    - name: version
      value: "nightly"
    - name: tag
      value: "4.10"
